apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: iamsajo/ecommerce-microservices-fastapi-order:9b29c3e02abfa76de75aeb63b1b54a869ac909b1
        ports:
        - containerPort: 5002
        env:
        - name: PAYMENT_SERVICE
          value: "payment-svc.default.svc.cluster.local:5003"
        - name: USER_SERVICE
          value: "user-svc.default.svc.cluster.local:5001"
        - name: PRODUCT_SERVICE
          value: "product-svc.default.svc.cluster.local:5004"
---
apiVersion: v1
kind: Service
metadata:
  name: order-svc
spec:
  selector:
    app: order
  ports:
  - port: 5002
    targetPort: 5002
