apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: iamsajo/ecommerce-microservices-nodejs-product:9b29c3e02abfa76de75aeb63b1b54a869ac909b1
        ports:
        - containerPort: 5004
---
apiVersion: v1
kind: Service
metadata:
  name: product-svc
spec:
  selector:
    app: product
  ports:
  - port: 5004
    targetPort: 5004
