apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: iamsajo/ecommerce-microservices-golang-main:308f6ee36f8414dd36a1385c627356c5668dddff
        ports:
        - containerPort: 5000
        env:
        - name: ORDER_SERVICE
          value: "order-svc.default.svc.cluster.local:5002"
        - name: PAYMENT_SERVICE
          value: "payment-svc.default.svc.cluster.local:5003"
        - name: USER_SERVICE
          value: "user-svc.default.svc.cluster.local:5001"
        - name: PRODUCT_SERVICE
          value: "product-svc.default.svc.cluster.local:5004"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
spec:
  type: LoadBalancer
  selector: 
    app: gateway
  ports:
  - port: 80
    targetPort: 5000
