# .github/workflows/cd.yml
name: CD - Deploy to Docker Hub

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      fastapi-order: ${{ steps.filter.outputs.fastapi-order }}
      nodejs-product: ${{ steps.filter.outputs.nodejs-product }}
      golang-user: ${{ steps.filter.outputs.golang-user }}
      flask-payment: ${{ steps.filter.outputs.flask-payment }}
      golang-main: ${{ steps.filter.outputs.golang-main }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            fastapi-order:
              - 'fastapi-order/**'
            nodejs-product:
              - 'nodejs-product/**'
            golang-user:
              - 'golang-user/**'
            flask-payment:
              - 'flask-payment/**'
            golang-main:
              - 'golang-main/**'

  build-and-push-fastapi-order:
    needs: detect-changes
    if: needs.detect-changes.outputs.fastapi-order == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/ecommerce-microservices-fastapi-order:${{ github.sha }}
          docker build -t $IMAGE ./fastapi-order
          docker push $IMAGE

      - name: Update image tag in order-svc.yaml
        run: |
          sed -i "s#image: .*/ecommerce-microservices-fastapi-order:.*#image: ${{ secrets.DOCKER_USERNAME }}/ecommerce-microservices-fastapi-order:${{ github.sha }}#g" k8s/order-svc.yaml

      - name: Commit & Push updated manifest
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add k8s/order-svc.yaml
          git commit -m "Update fastapi-order image to ${{ github.sha }}" || echo "No changes"

          # Pull latest changes and rebase before pushing
          git pull --rebase origin main || true
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  build-and-push-nodejs-product:
    needs: detect-changes
    if: needs.detect-changes.outputs.nodejs-product == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build & Push Docker image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/ecommerce-microservices-nodejs-product:${{ github.sha }}
          docker build -t $IMAGE ./nodejs-product
          docker push $IMAGE

      - name: Update image tag in product-svc.yaml
        run: |
          sed -i "s#image: .*/ecommerce-microservices-nodejs-product:.*#image: ${{ secrets.DOCKER_USERNAME }}/ecommerce-microservices-nodejs-product:${{ github.sha }}#g" k8s/product-svc.yaml

      - name: Commit & Push updated manifest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add k8s/product-svc.yaml
          git commit -m "Update nodejs-product image to ${{ github.sha }}" || echo "No changes"

          # Pull latest changes and rebase before pushing
          git pull --rebase origin main || true
          git push origin HEAD:main


  build-and-push-golang-user:
    needs: detect-changes
    if: needs.detect-changes.outputs.golang-user == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build & Push Docker image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/ecommerce-microservices-golang-user:${{ github.sha }}
          docker build -t $IMAGE ./golang-user
          docker push $IMAGE
      
      - name: Update image tag in user-svc.yaml
        run: |
          sed -i "s#image: .*/ecommerce-microservices-golang-user:.*#image: ${{ secrets.DOCKER_USERNAME }}/ecommerce-microservices-golang-user:${{ github.sha }}#g" k8s/user-svc.yaml

      - name: Commit updated manifest
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/user-svc.yaml
          git commit -m "Update golang-user image to ${{ github.sha }}" || echo "No changes"

          # Pull latest changes and rebase before pushing
          git pull --rebase origin main || true
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  build-and-push-flask-payment:
    needs: detect-changes
    if: needs.detect-changes.outputs.flask-payment == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/ecommerce-microservices-flask-payment:${{ github.sha }}
          docker build -t $IMAGE ./flask-payment
          docker push $IMAGE
  
      - name: Update image tag in payment-svc.yaml
        run: |
          sed -i "s#image: .*/ecommerce-microservices-flask-payment:.*#image: ${{ secrets.DOCKER_USERNAME }}/ecommerce-microservices-flask-payment:${{ github.sha }}#g" k8s/payment-svc.yaml

      - name: Commit updated manifest
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/payment-svc.yaml
          git commit -m "Update flask-payment image to ${{ github.sha }}" || echo "No changes"

          # Pull latest changes and rebase before pushing
          git pull --rebase origin main || true
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  build-and-push-gateway:
    needs: detect-changes
    if: needs.detect-changes.outputs.golang-main == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build & Push Docker image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/ecommerce-microservices-golang-main:${{ github.sha }}
          docker build -t $IMAGE ./golang-main
          docker push $IMAGE

      - name: Update image tag in gateway.yaml
        run: |
          sed -i "s#image: .*/ecommerce-microservices-golang-main:.*#image: ${{ secrets.DOCKER_USERNAME }}/ecommerce-microservices-golang-main:${{ github.sha }}#g" k8s/gateway.yaml

      - name: Commit updated manifest
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/gateway.yaml
          git commit -m "Update gateway image to ${{ github.sha }}" || echo "No changes"

          # Pull latest changes and rebase before pushing
          git pull --rebase origin main || true
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}